% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 25-Jan-2026 20:34:06
%
% This script assumes these variables are defined:
%
%   normalized_predictors_train - input data.
%   normalized_responses_train - target data.

rng(1);   % Fix random seed for reproducibility

x = normalized_predictors_train';
t = normalized_responses_train';

% Choose a Training Function
trainFcn = 'trainbr';  % Bayesian Regularization backpropagation.

% Create a Fitting Network
hiddenLayerSize = 90;
net_1 = fitnet(hiddenLayerSize, trainFcn);

% Setup Division of Data for Training, Validation, Testing
net_1.divideParam.trainRatio = 70/100;
net_1.divideParam.valRatio   = 15/100;
net_1.divideParam.testRatio  = 15/100;

% Train the Network
[net_1, tr] = train(net_1, x, t);

% Save the TRAINED network
save net_1 net_1 tr

% Predict output
y = net_1(x);

% Performance (MSE)
performance = perform(net_1, t, y)

% ================================
% Actual vs Predicted (Time Series)
% ================================
actual = t';
predicted = y';

figure;
plot(actual, 'b', 'LineWidth', 1.3); hold on;
plot(predicted, 'r--', 'LineWidth', 1.3);
legend('Actual Load', 'Predicted Load');
xlabel('Sample Index');
ylabel('Load (Normalized)');
title('Actual vs Predicted Load');
grid on;

% ================================
% Actual vs Predicted (Scatter)
% ================================
figure;
scatter(actual, predicted, 20, 'filled');
hold on;
plot([min(actual) max(actual)], [min(actual) max(actual)], 'k--', 'LineWidth', 1.2);
xlabel('Actual Load');
ylabel('Predicted Load');
title('Scatter Plot: Actual vs Predicted');
axis equal;
grid on;

% View the Network
view(net_1)
